### ISSUE TITLE
Should also work for .yml extension

### ISSUE THREAD

**Issue by schickling** [any-json/any-json#9]
Most people save the YAML files with `.yml`. Would be great if `any-json` could work with both `.yaml` and `.yml`.

**Comment by adamvoss** [comment]
What version of `any-json` are you using and what is the command are you running?

I tried to cover this case with 2b50ce5cd5948ec2a9c8708b5a6e5fcc1dcea58b which released in `3.0.0`, but I may have missed something.

**Comment by schickling** [comment]
I'm using the `pajv` CLI.

**Comment by adamvoss** [comment]
This issue was moved to json-schema-everywhere/pajv#3

**Comment by adamvoss** [comment]
The `any-json` CLI supports this.  I could be wrong in this preference, but I currently think it is better to keep the API restricted to specifying actual formats and make clients responsible for mapping file extensions to the proper format so I have moved this issue to the `pajv` repository.
